# tools/generate_report.py
"""
Tool 5: Generates PDF and Word clash coordination reports.
Files are saved locally to the outputs/ folder.
No external data transmission of any kind.
"""
import json
from pathlib import Path
from datetime import datetime
from config import OUTPUT_DIR


def run(args: dict) -> str:
    clashes      = args.get("clashes", [])
    project_name = args.get("project_name", "Unnamed Project")
    fmt          = args.get("format", "both")

    if isinstance(clashes, str):
        try:
            clashes = json.loads(clashes)
        except Exception:
            return json.dumps({"error": "Invalid clashes JSON."})

    if not clashes:
        return json.dumps({"error": "No clash data provided to generate report."})

    timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name  = project_name.replace(" ", "_").replace("/", "-")
    base_name  = f"ClashGuard_{safe_name}_{timestamp}"
    generated  = []
    errors     = []

    if fmt in ("docx", "both"):
        path = OUTPUT_DIR / f"{base_name}.docx"
        try:
            _generate_docx(clashes, project_name, path)
            generated.append(str(path))
        except ImportError:
            errors.append("python-docx not installed. Run: pip install python-docx")
        except Exception as e:
            errors.append(f"DOCX error: {str(e)}")

    if fmt in ("pdf", "both"):
        path = OUTPUT_DIR / f"{base_name}.pdf"
        try:
            _generate_pdf(clashes, project_name, path)
            generated.append(str(path))
        except ImportError:
            errors.append("reportlab not installed. Run: pip install reportlab")
        except Exception as e:
            errors.append(f"PDF error: {str(e)}")

    sev = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for c in clashes:
        sev[c.get("severity_label", "MEDIUM")] = sev.get(c.get("severity_label", "MEDIUM"), 0) + 1

    return json.dumps({
        "success":          len(generated) > 0,
        "files_generated":  generated,
        "errors":           errors,
        "total_clashes":    len(clashes),
        "severity_summary": sev,
        "message": (f"Report saved: {', '.join(generated)}" if generated
                    else f"Report generation failed: {'; '.join(errors)}")
    }, indent=2)


# ── Word Report ───────────────────────────────────────────────────

def _generate_docx(clashes: list, project_name: str, path: Path):
    from docx import Document
    from docx.shared import RGBColor, Pt

    SEVERITY_COLORS = {
        "CRITICAL": RGBColor(0xC0, 0x00, 0x00),
        "HIGH":     RGBColor(0xFF, 0x66, 0x00),
        "MEDIUM":   RGBColor(0xFF, 0xC0, 0x00),
        "LOW":      RGBColor(0x00, 0x70, 0xC0),
    }

    doc = Document()

    # Title
    doc.add_heading("ClashGuard MEP Coordination Report", 0)
    doc.add_heading(f"Project: {project_name}", 1)
    doc.add_paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}  |  "
        f"Total Clashes: {len(clashes)}  |  "
        f"Generated by: ClashGuard MCP v1.0"
    )
    doc.add_paragraph("")

    # Summary table
    doc.add_heading("Severity Summary", 2)
    sev = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for c in clashes:
        sev[c.get("severity_label", "MEDIUM")] = sev.get(c.get("severity_label", "MEDIUM"), 0) + 1

    table = doc.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    hdr[0].text = "Severity"
    hdr[1].text = "Count"
    hdr[2].text = "Required Action"

    actions = {
        "CRITICAL": "Immediate — block design sign-off",
        "HIGH":     "This sprint — before construction docs",
        "MEDIUM":   "Coordination meeting — can sleeve/penetrate",
        "LOW":      "Monitor — not blocking"
    }
    for sev_label, count in sev.items():
        row = table.add_row().cells
        row[0].text = sev_label
        row[1].text = str(count)
        row[2].text = actions[sev_label]

    doc.add_paragraph("")
    doc.add_heading("Clash Details", 2)

    for c in clashes:
        sev_label = c.get("severity_label", "MEDIUM")
        h = doc.add_heading(
            f"{c['clash_id']} — {sev_label}: "
            f"{c['element_a']['type']} vs {c['element_b']['type']}",
            level=3
        )
        run = h.runs[0] if h.runs else h.add_run()
        run.font.color.rgb = SEVERITY_COLORS.get(sev_label, RGBColor(0, 0, 0))

        doc.add_paragraph(
            f"Location: {c.get('location', 'Unknown')}  |  "
            f"Clash Type: {c['type'].upper()}  |  "
            f"Intersection Volume: {c.get('intersection_volume_m3', 0):.4f} m³"
        )
        doc.add_paragraph(
            f"Element A: {c['element_a']['name']} (ID: {c['element_a']['id']})"
        )
        doc.add_paragraph(
            f"Element B: {c['element_b']['name']} (ID: {c['element_b']['id']})"
        )
        doc.add_paragraph("")

    doc.save(str(path))


# ── PDF Report ────────────────────────────────────────────────────

def _generate_pdf(clashes: list, project_name: str, path: Path):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors
    from reportlab.lib.units import mm

    SEVERITY_COLORS_PDF = {
        "CRITICAL": colors.HexColor("#C00000"),
        "HIGH":     colors.HexColor("#FF6600"),
        "MEDIUM":   colors.HexColor("#FFC000"),
        "LOW":      colors.HexColor("#0070C0"),
    }

    doc    = SimpleDocTemplate(str(path), pagesize=A4,
                               rightMargin=20*mm, leftMargin=20*mm,
                               topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    story  = []

    # Title
    story.append(Paragraph("ClashGuard MEP Coordination Report", styles["Title"]))
    story.append(Paragraph(f"Project: {project_name}", styles["Heading1"]))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')} | "
        f"Total Clashes: {len(clashes)} | ClashGuard MCP v1.0",
        styles["Normal"]
    ))
    story.append(Spacer(1, 8*mm))

    # Summary
    story.append(Paragraph("Severity Summary", styles["Heading2"]))
    sev = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for c in clashes:
        sev[c.get("severity_label", "MEDIUM")] = sev.get(c.get("severity_label", "MEDIUM"), 0) + 1

    sev_data = [["Severity", "Count", "Action"]]
    for sl, cnt in sev.items():
        sev_data.append([sl, str(cnt),
                         {"CRITICAL":"Immediate","HIGH":"This sprint",
                          "MEDIUM":"Coordination","LOW":"Monitor"}[sl]])
    sev_table = Table(sev_data, colWidths=[40*mm, 20*mm, 100*mm])
    sev_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTSIZE",   (0, 0), (-1, -1), 9),
    ]))
    story.append(sev_table)
    story.append(Spacer(1, 8*mm))

    # Clash details
    story.append(Paragraph("Clash Details", styles["Heading2"]))
    for c in clashes:
        sl    = c.get("severity_label", "MEDIUM")
        color = SEVERITY_COLORS_PDF.get(sl, colors.black)
        style = ParagraphStyle("clash_head", parent=styles["Heading3"], textColor=color)
        story.append(Paragraph(
            f"{c['clash_id']} — {sl}: {c['element_a']['type']} vs {c['element_b']['type']}", style
        ))
        story.append(Paragraph(
            f"Location: {c.get('location','Unknown')} | "
            f"Type: {c['type'].upper()} | "
            f"Volume: {c.get('intersection_volume_m3', 0):.4f} m³",
            styles["Normal"]
        ))
        story.append(Spacer(1, 4*mm))

    doc.build(story)
