# tools/generate_report.py
"""
Tool 5: generate_report
Generates professional PDF and/or Word clash coordination reports.
"""

import json
from pathlib import Path
from datetime import datetime

OUTPUT_DIR = Path(__file__).parent.parent / "outputs"
OUTPUT_DIR.mkdir(exist_ok=True)

def run(args: dict) -> str:
    clashes      = args.get("clashes", [])
    project_name = args.get("project_name", "Unnamed Project")
    fmt          = args.get("format", "both")

    if isinstance(clashes, str):
        try:
            parsed = json.loads(clashes)
            if isinstance(parsed, dict):
                clashes = parsed.get("clashes", [])
            else:
                clashes = parsed
        except:
            return json.dumps({"error": "Invalid clash data."})
    elif isinstance(clashes, dict):
        clashes = clashes.get("clashes", [])

    if not clashes:
        return json.dumps({"error": "No clashes provided for report generation."})

    timestamp    = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name    = f"ClashGuard_Report_{project_name.replace(' ', '_')}_{timestamp}"
    generated    = []

    if fmt in ("docx", "both"):
        docx_path = OUTPUT_DIR / f"{base_name}.docx"
        _generate_docx(clashes, project_name, docx_path)
        generated.append(str(docx_path))

    if fmt in ("pdf", "both"):
        pdf_path = OUTPUT_DIR / f"{base_name}.pdf"
        _generate_pdf(clashes, project_name, pdf_path)
        generated.append(str(pdf_path))

    severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for c in clashes:
        severity_counts[c.get("severity_label", "MEDIUM")] += 1

    return json.dumps({
        "success":          True,
        "files_generated":  generated,
        "total_clashes":    len(clashes),
        "severity_summary": severity_counts,
        "message": f"Report generated: {len(generated)} file(s). Path: {', '.join(generated)}"
    }, indent=2)

def _generate_docx(clashes: list, project_name: str, path: Path):
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()
    doc.add_heading(f"ClashGuard Coordination Report", 0)
    doc.add_heading(f"Project: {project_name}", 1)

    info = doc.add_paragraph()
    info.add_run(f"Date: {datetime.now().strftime('%B %d, %Y')}  |  "
                 f"Total Clashes: {len(clashes)}  |  "
                 f"Generated by: ClashGuard MCP v1.0")

    severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for c in clashes:
        severity_counts[c.get("severity_label", "MEDIUM")] += 1

    doc.add_heading("Executive Summary", 2)
    doc.add_paragraph(
        f"ClashGuard detected {len(clashes)} MEP clashes in the {project_name} model. "
        f"Immediate attention required for {severity_counts['CRITICAL']} CRITICAL "
        f"and {severity_counts['HIGH']} HIGH severity clashes. "
        f"All geometry calculations were performed deterministically."
    )

    table = doc.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    hdr = table.rows[0].cells
    for i, h in enumerate(["Severity", "Count", "Action", "Timeline"]):
        hdr[i].text = h

    rows_data = [
        ("CRITICAL", str(severity_counts["CRITICAL"]), "Immediate action required", "Before next design iteration"),
        ("HIGH",     str(severity_counts["HIGH"]),     "Address this sprint",        "Within 3 days"),
        ("MEDIUM",   str(severity_counts["MEDIUM"]),   "Resolve before construction doc", "Within 2 weeks"),
        ("LOW",      str(severity_counts["LOW"]),      "Monitor and note",            "Before issue"),
    ]
    for r in rows_data:
        row_cells = table.add_row().cells
        for i, val in enumerate(r):
            row_cells[i].text = val

    doc.add_heading("Clash Details", 2)
    for c in clashes:
        doc.add_heading(f"{c['clash_id']} — {c['severity_label']}: {c['element_a']['type']} vs {c['element_b']['type']}", 3)
        doc.add_paragraph(
            f"Location: {c.get('location', 'Unknown')}  |  "
            f"Type: {c['type'].upper()} clash  |  "
            f"Volume: {c.get('intersection_volume_m3', 0):.4f} m³"
        )
        if c.get("ai_recommendation"):
            doc.add_paragraph(f"Recommendation: {c['ai_recommendation']}")

    doc.save(str(path))

def _generate_pdf(clashes: list, project_name: str, path: Path):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors
    from reportlab.lib.units import mm

    doc    = SimpleDocTemplate(str(path), pagesize=A4,
                               rightMargin=20*mm, leftMargin=20*mm,
                               topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    story  = []

    story.append(Paragraph("ClashGuard Coordination Report", styles["Title"]))
    story.append(Paragraph(f"Project: {project_name}", styles["Heading1"]))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')} | Total Clashes: {len(clashes)}", styles["Normal"]))
    story.append(Spacer(1, 10*mm))

    sev_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for c in clashes:
        sev_counts[c.get("severity_label", "MEDIUM")] += 1

    story.append(Paragraph("Summary", styles["Heading2"]))
    data = [["Severity", "Count"]] + [[k, str(v)] for k, v in sev_counts.items()]
    t = Table(data, colWidths=[80*mm, 40*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0052CC")),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F6FB")]),
    ]))
    story.append(t)
    story.append(Spacer(1, 10*mm))

    story.append(Paragraph("Clash Details", styles["Heading2"]))
    for c in clashes:
        story.append(Paragraph(
            f"<b>{c['clash_id']}</b> — {c['severity_label']}: "
            f"{c['element_a']['type']} vs {c['element_b']['type']} @ {c.get('location', 'Unknown')}",
            styles["Heading3"]
        ))
        story.append(Spacer(1, 3*mm))

    doc.build(story)
